[tool.poetry]
name = "target-permutation-importance"
version = "0.1.0"
description = ""
authors = ["Anthony Chiu <kingychiu@gmail.com>"]
readme = "README.md"
packages = [{include = "target_permutation_importance"}]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.25.0"
pandas = "^2.0.3"
polars = "^0.18.4"
scikit-learn = "^1.3.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.275"
black = "^23.3.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
